### ISSUE TITLE
Add toggles to disable roughness and metallic analysis

### ISSUE THREAD

**Issue by Rockbard** [semagnum/Material_Color_From_Nodes#5]
Hey, thank for the great addon. 
 Is there a way to leave out roughness and metallic values of the materials?

**Comment by semagnum** [comment]
Thank you! The roughness and metallic values are driven by what nodes it's given. For instance, if there's no PBR or glossy shaders, it ignores metallic and gives a default value (0 in this case, 0.5 for roughness).

But I'm guessing you mean "even if I have a PBR shader, I want the option to ignore setting the roughness or metallic values." That is not supported yet. Is that what you mean?

**Comment by Rockbard** [comment]
Yep, specifically I commented out these two lines below in the operator.py and got what I need

def set_material(material):
    if material.use_nodes:
        node_tree = material.node_tree
        output = next(util.find_outputs(node_tree), None)

        if output is not None:
            material.diffuse_color = node.assert_color(node.get_from_node(output, config.ALBEDO_MAP,
                                                                          Vector((0.8, 0.8, 0.8, 1.0))
                                                                          ))
            # material.roughness = node.assert_float(node.get_from_node(output, config.ROUGHNESS_MAP, 0.5))
            # material.metallic = node.assert_float(node.get_from_node(output, config.METALLIC_MAP, 0.0))

**Comment by semagnum** [comment]
Gotcha gotcha. That's a good idea though. I'll add this to the backlog of having roughness and metallic toggles above the buttons (unfortunately, there's no redo panel in the properties area).

**Comment by semagnum** [comment]
Added two toggles that works for all the operators (both in the panel and Python API, if preferred).

Try the most recent changes. Be sure to uninstall the old version, restart Blender, then install the new version to ensure only the new changes remain.

**Comment by Rockbard** [comment]
Works as intended. But current UI situation could be better. 
![Screenshot 2024-04-28 113217](https://github.com/semagnum/Material_Color_From_Nodes/assets/39404436/d64d9a3a-cc88-4f0c-abea-0bb2c01a14ae)

I've tried to put the toggles in one row, but they are justified to the right which is also not ideal. 
![Screenshot 2024-04-28 115122](https://github.com/semagnum/Material_Color_From_Nodes/assets/39404436/79520f33-aac4-4be9-8612-33bd84044750)

Maybe to put them into preferences under the add-ons tab.

**Comment by semagnum** [comment]
> current UI situation could be better

The central column UI is intentional, to follow the Blender interface style in other areas, including other material panels:

![Screenshot from Blender's material properties, which are aligned around a central lign](https://github.com/semagnum/Material_Color_From_Nodes/assets/46832095/1d753674-6a04-46d3-b72a-1cf02de9a159)

I know I have a row of buttons just below. I don't know if operators support headings in `UILayout` yet, I may look into that next. But I'd rather push for consistency with the existing Blender UI (as inconsistent as it can be sometimes 😝). The dev's decision on the UI central column layout is outlined here: [devtalk.blender.org/t/single-column-layout-suggestion-to-have-text-left-aligned/1704/55](https://devtalk.blender.org/t/single-column-layout-suggestion-to-have-text-left-aligned/1704/55). But regardless, the my buttons' layout is outside the scope of this change.

However, if you'd still like a row for your installation: remove the following lines of code from `panel.py` while keeping your row changes. This will disable the central alignment:

```py
layout.use_property_split = True
layout.use_property_decorate = False  # No animation
```

**Comment by Rockbard** [comment]
No worries, I reached my goals anyway. 
Thank you for being so responsive and swift.

**Comment by semagnum** [comment]
Of course! Glad I could help 😊

Closing this issue.
